[workspace]
members = [
    "crates/apecs",
    "crates/apecs-derive",
    "crates/apecs-derive-canfetch",
    "crates/benchmarks",
    "crates/xtask",
]

resolver = "2"

[profile.bench]
debug = true
