[package]
name = "apecs"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["gamedev", "ecs", "async"]
readme = "../../README.md"
documentation = "https://docs.rs/apecs/"
repository = "https://github.com/schell/apecs"
categories = ["concurrency", "game-engines"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "apecs"
path = "src/lib.rs"

[[bin]]
name = "apecs_example"
path = "src/main.rs"

[dependencies]
anyhow = "^1.0"
apecs-derive = { version = "^0.1", path = "../apecs-derive" }
smol = "^1.2"
smol-potat = "^1.0"
tracing = "^0.1"
tracing-subscriber = "^0.3"

[dev-dependencies]
criterion = "^0.3"

[[bench]]
name = "benchmark"
harness = false
