[package]
name = "apecs"
version = "0.1.4"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["gamedev", "ecs", "async"]
readme = "../../README.md"
documentation = "https://docs.rs/apecs/"
repository = "https://github.com/schell/apecs"
categories = ["concurrency", "game-engines"]
description = "An asyncronous and parallel entity-component system"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
debug-async = []

[lib]
name = "apecs"
path = "src/lib.rs"
bench = false

[[bin]]
name = "apecs_example"
path = "src/main.rs"
bench = false

[dependencies]
anyhow = "^1.0"
apecs-derive = { version = "0.1.3", path = "../apecs-derive" }
async-broadcast = "^0.4"
hibitset = "^0.6"
rayon = "^1.5"
rustc-hash = "^1.1"
smol = "^1.2"
tracing = "^0.1"
tracing-subscriber = "^0.3"

[dev-dependencies]
bevy_ecs = "0.5.0"
bevy_tasks = "0.5.0"
cgmath = { version = "0.17", features = ["serde"] }
criterion = "^0.3"
hecs = { version = "0.5", features = ["column-serialize", "row-serialize"] }
legion = "0.3"
planck_ecs = { version = "1.1.0", features = ["parallel"] }
shipyard = "0.5.0"
specs = {version = "0.16.1", features = ["serde"] }
specs-derive = "0.4.1"

[[bench]]
name = "benchmark"
harness = false
